// ═══════════════════════════════════════════════════════════════
//  التحقق من البريد الإلكتروني ومنع البريد المؤقت (Anti-Disposable Email)
//  • يدعم كبرى المزودات الموثوقة: Google (Gmail), Microsoft (Outlook/Hotmail),
//    Yahoo, Apple (iCloud), Proton, Zoho, Fastmail, وغيرها.
//  • يدعم النطاقات التعليمية والحكومية الرسمية (.edu, .edu.eg, .gov...).
//  • يحظر تمامًا كافة خدمات الإيميل المؤقت والمهمل (Temp Mail / 10MinuteMail).
// ═══════════════════════════════════════════════════════════════

import { EMAIL_RE } from "./validation";

// قائمة أشهر خدمات البريد المؤقت والمزيف عالميًا وعربيًا
const DISPOSABLE_DOMAINS = new Set([
  // المزودات العربية للمهمل والمؤقت
  "mohmal.com",
  "mohmal.im",
  "mohmal.in",
  "mohmal.tech",
  "tempmail.ge",
  "muellmail.com",
  "fakemail.net",
  "arabaemail.com",
  "emailfake.com",
  "barid.top",
  "al-mail.com",
  "arabymail.com",
  "yopmail.fr",

  // مزودات عالمية شائعة للبريد المؤقت (10Minute, TempMail, Guerrilla...)
  "10minutemail.com",
  "10minutemail.net",
  "10minutemail.org",
  "10minemail.com",
  "10minutemailbox.com",
  "tempmail.com",
  "temp-mail.org",
  "temp-mail.io",
  "tempmailo.com",
  "tempmailgen.com",
  "tempail.com",
  "guerrillamail.com",
  "guerrillamail.net",
  "guerrillamail.org",
  "guerrillamail.biz",
  "guerrillamailblock.com",
  "sharklasers.com",
  "grr.la",
  "spam4.me",
  "pokemail.net",
  "mailinator.com",
  "mailinator.net",
  "mailin8r.com",
  "binkmail.com",
  "bobmail.info",
  "chammy.info",
  "devnullmail.com",
  "letthemeatspam.com",
  "mailinater.com",
  "suremail.info",
  "zippymail.info",
  "throwawaymail.com",
  "yopmail.com",
  "yopmail.net",
  "cool.fr.nf",
  "jetable.fr.nf",
  "courriel.fr.nf",
  "moncourrier.fr.nf",
  "monemail.fr.nf",
  "monmail.fr.nf",
  "hide.biz.st",
  "mymail.infos.st",
  "getnada.com",
  "abaca.com",
  "abacaba.com",
  "nada.ltd",
  "nada.email",
  "inboxbear.com",
  "dispostable.com",
  "fakeinbox.com",
  "trashmail.com",
  "trashmail.net",
  "trashmail.me",
  "burnermail.io",
  "mytemp.email",
  "generator.email",
  "tempr.email",
  "discard.email",
  "discardmail.com",
  "spambog.com",
  "spambog.de",
  "spambog.ru",
  "emailondeck.com",
  "dropmail.me",
  "crazymailing.com",
  "maildrop.cc",
  "inboxkitten.com",
  "fakemailgenerator.com",
  "armyspy.com",
  "cuvox.de",
  "dayrep.com",
  "fleckens.hu",
  "gustr.com",
  "jourrapide.com",
  "rhyta.com",
  "superrito.com",
  "teleworm.us",
  "einrot.com",
  "chacuo.net",
  "0-mail.com",
  "0815.ru",
  "0clickemail.com",
  "0wnd.net",
  "0wnd.org",
  "10mail.org",
  "20minutemail.com",
  "20minutemail.it",
  "33mail.com",
  "anonaddy.com",
  "anonaddy.me",
  "anonymouse.org",
  "antichef.com",
  "antichef.net",
  "brefmail.com",
  "bugmenot.com",
  "byom.de",
  "clipmail.eu",
  "cmail.club",
  "cmail.com",
  "cmail.net",
  "cmail.org",
  "crazymailing.com",
  "cust.in",
  "daum.net",
  "deadaddress.com",
  "despam.it",
  "despammed.com",
  "discardmail.de",
  "disposable.com",
  "disposableaddress.com",
  "disposableinbox.com",
  "disposablemail.com",
  "disposemail.com",
  "dontreg.com",
  "dumpmail.de",
  "easytrashmail.com",
  "emailigo.de",
  "emailmiser.com",
  "emailproxsy.com",
  "emailsensei.com",
  "emailtemporaneo.com",
  "emailtemporaneo.net",
  "emailtemporar.ro",
  "emailtemporario.com.br",
  "emailthe.net",
  "emailto.de",
  "emailwarden.com",
  "emailx.at.tc",
  "emailx.eu.tc",
  "emltmp.com",
  "emz.net",
  "ephemail.net",
  "evopirate.com",
  "eyepaste.com",
  "fakemailz.com",
  "fastcheetah.com",
  "fasttrashmail.com",
  "filzmail.com",
  "flemail.ru",
  "flyspam.com",
  "free-email.co.uk",
  "freeletter.me",
  "freemail.ms",
  "front14.org",
  "fudgecake.com",
  "get10mail.com",
  "get2mail.fr",
  "getairmail.com",
  "getonemail.com",
  "gishpuppy.com",
  "gowikicars.com",
  "greensloth.com",
  "gsrv.co.uk",
  "guerrillamail.de",
  "h8s.org",
  "haltospam.com",
  "harakirimail.com",
  "hartbot.de",
  "hatespam.org",
  "hotpop.com",
  "incognitomail.org",
  "instant-mail.de",
  "instantemailaddress.com",
  "ipoo.org",
  "ironymail.com",
  "ispep.com",
  "itshappening.net",
  "jetable.com",
  "jetable.net",
  "jetable.org",
  "kasmail.com",
  "keepmymail.com",
  "killmail.net",
  "klzlk.com",
  "koszmail.pl",
  "kurzepost.de",
  "lhsdv.com",
  "lifebyfood.com",
  "link2mail.net",
  "litedrop.com",
  "lookugly.com",
  "lopl.com",
  "m4il.net",
  "mail-temporaire.fr",
  "mail.by",
  "mail.misterpinball.de",
  "mail.ru",
  "mail1a.de",
  "mailcatch.com",
  "mailchop.com",
  "mailcube.net",
  "maileater.com",
  "mailexpire.com",
  "mailforspam.com",
  "mailfreeonline.com",
  "mailhazard.com",
  "mailhazard.us",
  "mailimate.com",
  "mailinblack.com",
  "mailme.ir",
  "mailmoat.com",
  "mailnesia.com",
  "mailnull.com",
  "mailslite.com",
  "mailspeed.ru",
  "mailtothis.com",
  "mailtrash.net",
  "mailzi.ru",
  "makememail.com",
  "meltmail.com",
  "mintemail.com",
  "misterpinball.de",
  "mobi.web.id",
  "mohmal.club",
  "msgsafe.io",
  "mycleaninbox.net",
  "mytrashmail.com",
  "neomailbox.com",
  "netmails.net",
  "noclickemail.com",
  "nomail.xl.cx",
  "nospam.ze.tc",
  "nospam4.us",
  "nospamfor.us",
  "notsharingmy.info",
  "nowmymail.com",
  "objectmail.com",
  "oneoffemail.com",
  "onetimeusemail.com",
  "owlpic.com",
  "pookmail.com",
  "postacin.com",
  "privacy.net",
  "proxymail.eu",
  "prtnx.com",
  "quickinbox.com",
  "rcpt.at",
  "reallymymail.com",
  "recursor.net",
  "reginbox.com",
  "safetymail.info",
  "safetypost.de",
  "sandvikcoromant.com",
  "saynotospams.com",
  "secure-mail.biz",
  "selfdestructingmail.com",
  "sendfree.eu",
  "shieldemail.com",
  "shiftmail.com",
  "shortmail.net",
  "sibmail.com",
  "sinnlos-mail.de",
  "skeefmail.com",
  "slopsbox.com",
  "sltrash.de",
  "smartinbox.co.uk",
  "smellfear.com",
  "sneakemail.com",
  "sofort-mail.de",
  "sogetthis.com",
  "soodonims.com",
  "spam.la",
  "spam.su",
  "spamavert.com",
  "spambox.info",
  "spambox.us",
  "spamcan.org",
  "spamcon.org",
  "spamcorptastic.com",
  "spamcowboy.com",
  "spamday.com",
  "spamfree24.org",
  "spamgourmet.com",
  "spamgourmet.net",
  "spamgourmet.org",
  "spamhole.com",
  "spaminator.de",
  "spaml.com",
  "spaml.de",
  "spammotel.com",
  "spamoff.de",
  "spampal.org",
  "spamtrap.ro",
  "speed.1s.fr",
  "superstachel.de",
  "suremail.info",
  "sweetxxx.de",
  "tafmail.com",
  "teewars.org",
  "temp-mail.ru",
  "tempemail.biz",
  "tempemail.co.za",
  "tempemail.net",
  "tempinbox.co.uk",
  "tempinbox.com",
  "tempmail.eu",
  "tempmail.it",
  "tempmail.net",
  "tempmail2.com",
  "temporaryemail.net",
  "temporaryforwarding.com",
  "temporaryinbox.com",
  "temppost.com",
  "throwawayemailaddress.com",
  "tmail.com",
  "tmailor.com",
  "trash-mail.at",
  "trash-mail.com",
  "trash-mail.de",
  "trash-me.com",
  "trashbox.eu",
  "trashcanmail.com",
  "trashmail.at",
  "trashmail.de",
  "trashmail.io",
  "trashmail.org",
  "trashmailer.com",
  "trashymail.com",
  "tyldd.com",
  "uggsrock.com",
  "valemail.net",
  "vefsida.com",
  "veryrealemail.com",
  "vidavee.com",
  "vmani.com",
  "wegwerfadresse.de",
  "wegwerfemail.de",
  "wegwerfmail.de",
  "wegwerfmail.net",
  "wegwerfmail.org",
  "whyspam.me",
  "willselfdestruct.com",
  "winemaven.in",
  "wuzup.net",
  "wuzupmail.net",
  "xent.com",
  "xmaily.com",
  "xoxy.net",
  "ypmail.webcam",
  "zehnminutenmail.de",
  "zippymail.info",
  "zoemail.com",
  "zxcvbnm.co.uk",
]);

// كلمات مشبوهة في نطاق البريد تدل على أنه مؤقت
const SUSPICIOUS_SUBSTRINGS = [
  "tempmail",
  "disposable",
  "throwaway",
  "fakeemail",
  "fakemail",
  "trashmail",
  "10minute",
  "10min",
  "20min",
  "guerrilla",
  "mailinator",
  "mohmal",
  "sharklasers",
  "burnermail",
  "emailondeck",
  "yopmail",
  "getnada",
  "wegwerf",
  "spambog",
  "inboxkitten",
];

// أشهر النطاقات الموثوقة عالميًا (للأداء السريع)
const TRUSTED_DOMAINS = new Set([
  // Google
  "gmail.com",
  "googlemail.com",
  // Microsoft
  "outlook.com",
  "hotmail.com",
  "live.com",
  "msn.com",
  "windowslive.com",
  "outlook.sa",
  "outlook.eg",
  "hotmail.co.uk",
  "hotmail.fr",
  // Yahoo
  "yahoo.com",
  "ymail.com",
  "rocketmail.com",
  "yahoo.co.uk",
  "yahoo.fr",
  "yahoo.es",
  "yahoo.de",
  "yahoo.com.eg",
  // Apple
  "icloud.com",
  "me.com",
  "mac.com",
  // Proton
  "proton.me",
  "protonmail.com",
  "pm.me",
  // Other Reputable
  "zoho.com",
  "aol.com",
  "gmx.com",
  "gmx.net",
  "mail.com",
  "fastmail.com",
  "hey.com",
  "tutanota.com",
  "tutamail.com",
]);

/**
 * فحص ما إذا كان النطاق مؤقتًا أو غير مسموح به
 */
export function isDisposableEmailDomain(domain: string): boolean {
  const d = domain.trim().toLowerCase();

  // 1) إذا كان في القائمة الموثوقة مباشرة ➔ مسموح
  if (TRUSTED_DOMAINS.has(d)) return false;

  // 2) نطاق تعليمي أو حكومي (.edu, .edu.eg, .gov, .ac...) ➔ مسموح ومرحب به
  if (
    d.endsWith(".edu") ||
    d.endsWith(".edu.eg") ||
    d.endsWith(".gov") ||
    d.endsWith(".gov.eg") ||
    d.includes(".ac.") ||
    d.endsWith(".edu.sa")
  ) {
    return false;
  }

  // 3) التحقق من القائمة السوداء للنطاقات المؤقتة
  if (DISPOSABLE_DOMAINS.has(d)) return true;

  // 4) التحقق من الكلمات المشبوهة في النطاق (مثل tempmail, mohmal...)
  for (const s of SUSPICIOUS_SUBSTRINGS) {
    if (d.includes(s)) return true;
  }

  return false;
}

/**
 * التحقق الكامل من بريد التسجيل:
 * 1) الصلاحية الشكلية (Regex)
 * 2) حظر البريد المؤقت والمهمل
 */
export function validateRegistrationEmail(email: string): { ok: boolean; error?: string } {
  const trimmed = (email || "").trim().toLowerCase();

  if (!trimmed) {
    return { ok: false, error: "أدخل بريدك الإلكتروني" };
  }

  if (!EMAIL_RE.test(trimmed)) {
    return { ok: false, error: "صيغة البريد الإلكتروني غير صحيحة" };
  }

  const atIndex = trimmed.lastIndexOf("@");
  if (atIndex === -1 || atIndex === trimmed.length - 1) {
    return { ok: false, error: "صيغة البريد الإلكتروني غير صحيحة" };
  }

  const domain = trimmed.slice(atIndex + 1);

  if (isDisposableEmailDomain(domain)) {
    return {
      ok: false,
      error:
        "غير مسموح بالتسجيل بالبريد المؤقت (مثل المهمل أو 10MinuteMail). يُرجى استخدام بريدك الشخصي الرسمي (Gmail, Outlook, Yahoo...) لضمان استلام رمز التفعيل وشهاداتك.",
    };
  }

  return { ok: true };
}
